{
  isgradequery: true,
  isbatoperate: true,
  isoperate: false,
  isfresh: true,
  isselect: true,
  batoperate: {
    export_excel: function (_this) {
      _this.$request(_this.pageconfig.queryapi.method, _this.pageconfig.queryapi.url, {
        pageindex: 1,
        pagesize: 65535,
        search_condition: _this.queryform.search_condition
      }).then(function (res) {
        if (res.code === 1) {
          let expdatalist = res.list;
          _this.export_handle(_this.pageconfig.fields, expdatalist);
        } else if (res.code === 0) {
          _this.$message.error(res.msg);
        }
      });
    },
  },
  pagefuns: {},
  fields: [{
      coltype: 'list',
      label: '生产线',
      prop: 'scx',
      dbprop: 'scx',
      overflowtooltip: true,
      headeralign: 'center',
      align: 'center',
      width: 80,
      inioptionapi: {
        method: 'get',
        url: '/ducar/baseinfo/scx'
      },
      hideoptionval: true,
      options: []
    }, {
      coltype: 'string',
      label: '岗位编码',
      prop: 'gwh',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },{
      coltype: 'string',
      label: '订单号',
      prop: 'order_no',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '机号',
      prop: 'engine_no',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '状态编码',
      prop: 'status_no',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'datetime',
      label: '故障编码',
      prop: 'fault_no',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '故障现象',
      prop: 'gzxx',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },{
      coltype: 'string',
      label: '检测部件',
      prop: 'jcbj',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '检测部件',
      prop: 'jcbj',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '处理岗位',
      prop: 'jyclgw',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '处理岗位',
      prop: 'jyclgw',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '检测人',
      prop: 'jcry',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'datetime',
      label: '检测时间',
      prop: 'jcsj',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '处理方式',
      prop: 'clfs',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '实际处理岗位',
      prop: 'sjclgw',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '原因分析',
      prop: 'yyfx',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '处理结果',
      prop: 'cljg',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '返修人',
      prop: 'fxr',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'datetime',
      label: '返修时间',
      prop: 'fxsj',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '闭环标志',
      prop: 'bhbz',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'string',
      label: '闭环人',
      prop: 'bhr',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    },
	{
      coltype: 'datetime',
      label: '闭环时间',
      prop: 'bhsj',
      overflowtooltip: true,
      sortable: true,
      headeralign: 'center',
      align: 'center',
    }
  ],
  form: {
    isdb: false,
    isedit: true
  },
  addapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  editapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  delapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  queryapi: {
    url: '/ducar/fxmx/list',
    method: 'post',
    callback: function (vm, res) {},
  },
}
