{
  isgradequery: true,
  isbatoperate: false,
  isoperate: false,
  isfresh: true,
  isselect: false,
  operate_fnlist: [],
  pagefuns: {},
  fields: [{
      coltype: 'string',
      prop: 'sbbh',
      label: '设备编号',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'string',
      prop: 'sbzbh',
      label: '设备自编号',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  overflowtooltip: true,
    },
	{
      coltype: 'string',
      prop: 'sbmc',
      label: '设备名称',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:200,
	  overflowtooltip: true,
    },
	{
      coltype: 'string',
      prop: 'sblx',
      label: '设备类型',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'string',
      prop: 'ip',
      label: '设备IP',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'string',
      prop: 'port',
      label: '设备端口',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'string',
      prop: 'gwh',
      label: '所在岗位',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'string',
      prop: 'lrr',
      label: '录入人',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    },
	{
      coltype: 'datetime',
      prop: 'lrsj',
      label: '录入时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }
  ],
  form: {
    isdb: false,
    isedit: true
  },
  addapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  editapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  delapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  queryapi: {
    url: '/cdgc/sbgl/list',
    method: 'post',
    callback: function (vm, res) {},
  },
}
