{
  isgradequery: true,
  isbatoperate: false,
  isoperate: false,
  isfresh: true,
  isselect: false,
  operate_fnlist: [],
  pagefuns: {},
  fields: [
  {
      coltype: 'string',
      prop: 'bjzt',
      label: '报警主体',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:130,
    },
	{
      coltype: 'string',
      prop: 'ycyy',
      label: '异常原因',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:130,
	  overflowtooltip: true,
    },
	{
      coltype: 'string',
      prop: 'sbbh',
      label: '设备编号',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:130,
    },
	{
      coltype: 'string',
      prop: 'gzdm',
      label: '故障代码',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:130,
    },
	{
      coltype: 'string',
      prop: 'gzxx',
      label: '故障信息',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:130,
	  overflowtooltip: true,
    },
	{
      coltype: 'string',
      prop: 'gzdj',
      label: '故障等级',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:100,
    },
	{
      coltype: 'datetime',
      prop: 'zlyckssj',
	  dbprop: 'zlyc_kssj',
      label: '质量异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'datetime',
      prop: 'sbyckssj',
	  dbprop: 'sbyc_kssj',
      label: '设备异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'datetime',
      prop: 'wlyckssj',
	  dbprop: 'wlyc_kssj',
      label: '物料异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'datetime',
      prop: 'qtyckssj',
	  dbprop: 'qtyc_kssj',
      label: '其它异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'datetime',
      prop: 'djyckssj',
	  dbprop:'djyc_kssj',
      label: '刀具异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'datetime',
      prop: 'jjyckssj',
	  dbprop:'jjyc_kssj',
      label: '夹具异常开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:170,
    },
	{
      coltype: 'string',
      prop: 'lrr',
      label: '录入人',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:100,
    },
	{
      coltype: 'datetime',
      prop: 'lrsj',
      label: '录入时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:200,
	  overflowtooltip: true,
    },
	{
      coltype: 'string',
      prop: 'bhlrr',
      label: '闭环人',
      headeralign: 'center',
      align: 'center',
      sortable: true,
	  width:100,
    }
  ],
  form: {
    isdb: false,
    isedit: true
  },
  addapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  editapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  delapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  queryapi: {
    url: '/cdgc/cdycgl/list',
    method: 'post',
    callback: function (vm, res) {},
  },
}
