{
  isgradequery: true,
  isbatoperate: false,
  isoperate: false,
  isfresh: true,
  isselect: false,
  operate_fnlist: [],
  pagefuns: {},
  fields: [{
      coltype: 'string',
      prop: 'bjzt',
      label: '报警主体',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'ycyy',
      label: '异常原因',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'sbbh',
      label: '设备编号',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'gzdm',
      label: '故障代码',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'gzxx',
      label: '故障信息',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'gzdj',
      label: '故障等级',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'datetime',
      prop: 'kssj',
      label: '开始时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'datetime',
      prop: 'jssj',
      label: '结束时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'ycsj',
      label: '时长',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'lrr',
      label: '录入人',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'datetime',
      prop: 'lrsj',
      label: '录入时间',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }, {
      coltype: 'string',
      prop: 'bhlrr',
      label: '闭环人',
      headeralign: 'center',
      align: 'center',
      sortable: true,
    }
  ],
  form: {
    isdb: false,
    isedit: true
  },
  addapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  editapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  delapi: {
    url: '',
    method: 'post',
    callback: function (vm, res) {},
  },
  queryapi: {
    url: '/cdgc/cdycgl/ycls_list',
    method: 'post',
    callback: function (vm, res) {},
  },
}
